<header>
	<h1>Example.com</h1>
</header>
<nav>
	<ul>
		<li id="home-main-menu-option">
			<a href="home.html">Home</a>
		</li>
		<li id="about-us-main-menu-option">
			<a href="about-us.html">About Us</a>
		</li>
		<li id="features-main-menu-option">
			<a href="features.html">Features</a>
		</li>
		<li id="contact-us-main-menu-option">
			<a href="contact-us.html">Contact Us</a>
		</li>
	</ul>
</nav>